# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    'APIKeySource',
    'IntegrationConnectionType',
    'IntegrationPassthroughBehavior',
    'IntegrationType',
    'Method',
    'RequestValidator',
]


@pulumi.type_token("aws-apigateway:index:APIKeySource")
class APIKeySource(_builtins.str, Enum):
    HEADER = "HEADER"
    AUTHORIZER = "AUTHORIZER"


@pulumi.type_token("aws-apigateway:index:IntegrationConnectionType")
class IntegrationConnectionType(_builtins.str, Enum):
    INTERNET = "INTERNET"
    VP_C_LINK = "VPC_LINK"


@pulumi.type_token("aws-apigateway:index:IntegrationPassthroughBehavior")
class IntegrationPassthroughBehavior(_builtins.str, Enum):
    WHEN_NO_MATCH = "when_no_match"
    WHEN_NO_TEMPLATES = "when_no_templates"
    NEVER = "never"


@pulumi.type_token("aws-apigateway:index:IntegrationType")
class IntegrationType(_builtins.str, Enum):
    AWS = "aws"
    AWS_PROXY = "aws_proxy"
    HTTP = "http"
    HTTP_PROXY = "http_proxy"
    MOCK = "mock"


@pulumi.type_token("aws-apigateway:index:Method")
class Method(_builtins.str, Enum):
    ANY = "ANY"
    GET = "GET"
    PUT = "PUT"
    POST = "POST"
    DELETE = "DELETE"
    PATCH = "PATCH"
    OPTIONS = "OPTIONS"
    HEAD = "HEAD"


@pulumi.type_token("aws-apigateway:index:RequestValidator")
class RequestValidator(_builtins.str, Enum):
    ALL = "ALL"
    PARAM_S_ONLY = "PARAMS_ONLY"
    BOD_Y_ONLY = "BODY_ONLY"
