// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package apigateway

type APIKeySource string

const (
	APIKeySourceHEADER     = APIKeySource("HEADER")
	APIKeySourceAUTHORIZER = APIKeySource("AUTHORIZER")
)

type IntegrationConnectionType string

const (
	IntegrationConnectionTypeINTERNET  = IntegrationConnectionType("INTERNET")
	IntegrationConnectionType_VPC_LINK = IntegrationConnectionType("VPC_LINK")
)

type IntegrationPassthroughBehavior string

const (
	IntegrationPassthroughBehavior_When_no_match     = IntegrationPassthroughBehavior("when_no_match")
	IntegrationPassthroughBehavior_When_no_templates = IntegrationPassthroughBehavior("when_no_templates")
	IntegrationPassthroughBehaviorNever              = IntegrationPassthroughBehavior("never")
)

type IntegrationType string

const (
	IntegrationTypeAws         = IntegrationType("aws")
	IntegrationType_Aws_proxy  = IntegrationType("aws_proxy")
	IntegrationTypeHttp        = IntegrationType("http")
	IntegrationType_Http_proxy = IntegrationType("http_proxy")
	IntegrationTypeMock        = IntegrationType("mock")
)

type Method string

const (
	MethodANY     = Method("ANY")
	MethodGET     = Method("GET")
	MethodPUT     = Method("PUT")
	MethodPOST    = Method("POST")
	MethodDELETE  = Method("DELETE")
	MethodPATCH   = Method("PATCH")
	MethodOPTIONS = Method("OPTIONS")
	MethodHEAD    = Method("HEAD")
)

type RequestValidator string

const (
	RequestValidatorALL          = RequestValidator("ALL")
	RequestValidator_PARAMS_ONLY = RequestValidator("PARAMS_ONLY")
	RequestValidator_BODY_ONLY   = RequestValidator("BODY_ONLY")
)

func init() {
}
