// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package apigateway

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/apigateway"
	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type RestAPI struct {
	pulumi.ResourceState

	// The underlying RestAPI resource.
	Api apigateway.RestApiOutput `pulumi:"api"`
	// The underlying RestAPIPolicy resource.
	ApiPolicy apigateway.RestApiPolicyOutput `pulumi:"apiPolicy"`
	// The underlying Deployment resource.
	Deployment apigateway.DeploymentOutput `pulumi:"deployment"`
	// The underlying Stage resource.
	Stage apigateway.StageOutput `pulumi:"stage"`
	// The URL where the Rest API is exposed.
	Url pulumi.StringOutput `pulumi:"url"`
}

// NewRestAPI registers a new resource with the given unique name, arguments, and options.
func NewRestAPI(ctx *pulumi.Context,
	name string, args *RestAPIArgs, opts ...pulumi.ResourceOption) (*RestAPI, error) {
	if args == nil {
		args = &RestAPIArgs{}
	}

	var resource RestAPI
	err := ctx.RegisterRemoteComponentResource("apigateway:index:RestAPI", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type restAPIArgs struct {
	// The source for the apikey. This can either be a HEADER or AUTHORIZER. If `apiKeyRequired` is
	// set to true on a route, and this is not defined the value will default to HEADER.
	ApiKeySource *APIKeySource `pulumi:"apiKeySource"`
	// Define custom gateway responses for the API. This can be used to properly enable
	// CORS for Lambda Authorizers.
	GatewayResponses map[string]SwaggerGatewayResponse `pulumi:"gatewayResponses"`
	// Request Validator specifies the validator to use at the API level. Note method level validators
	// override this.
	RequestValidator *RequestValidator `pulumi:"requestValidator"`
	// Routes to use to initialize the APIGateway.  These will be used to create the Swagger
	// specification for the API.
	//
	// Either `swaggerString` or `routes` must be specified.
	Routes []Route `pulumi:"routes"`
	// The stage name for your API. This will get added as a base path to your API url.
	StageName *string `pulumi:"stageName"`
	// Bucket to use for placing resources for static resources.  If not provided a default one will
	// be created on your behalf if any `StaticRoute`s are provided.
	StaticRoutesBucket *s3.Bucket `pulumi:"staticRoutesBucket"`
	// A Swagger specification already in string form to use to initialize the APIGateway.  Note
	// that you must manually provide permission for any route targets to be invoked by API Gateway
	// when using `swaggerString`.
	//
	// Either `swaggerString` or `routes` must be specified.
	SwaggerString *string `pulumi:"swaggerString"`
}

// The set of arguments for constructing a RestAPI resource.
type RestAPIArgs struct {
	// The source for the apikey. This can either be a HEADER or AUTHORIZER. If `apiKeyRequired` is
	// set to true on a route, and this is not defined the value will default to HEADER.
	ApiKeySource *APIKeySource
	// Define custom gateway responses for the API. This can be used to properly enable
	// CORS for Lambda Authorizers.
	GatewayResponses map[string]SwaggerGatewayResponseInput
	// Request Validator specifies the validator to use at the API level. Note method level validators
	// override this.
	RequestValidator *RequestValidator
	// Routes to use to initialize the APIGateway.  These will be used to create the Swagger
	// specification for the API.
	//
	// Either `swaggerString` or `routes` must be specified.
	Routes []RouteArgs
	// The stage name for your API. This will get added as a base path to your API url.
	StageName pulumi.StringPtrInput
	// Bucket to use for placing resources for static resources.  If not provided a default one will
	// be created on your behalf if any `StaticRoute`s are provided.
	StaticRoutesBucket s3.BucketInput
	// A Swagger specification already in string form to use to initialize the APIGateway.  Note
	// that you must manually provide permission for any route targets to be invoked by API Gateway
	// when using `swaggerString`.
	//
	// Either `swaggerString` or `routes` must be specified.
	SwaggerString pulumi.StringPtrInput
}

func (RestAPIArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*restAPIArgs)(nil)).Elem()
}

type RestAPIInput interface {
	pulumi.Input

	ToRestAPIOutput() RestAPIOutput
	ToRestAPIOutputWithContext(ctx context.Context) RestAPIOutput
}

func (*RestAPI) ElementType() reflect.Type {
	return reflect.TypeOf((*RestAPI)(nil))
}

func (i *RestAPI) ToRestAPIOutput() RestAPIOutput {
	return i.ToRestAPIOutputWithContext(context.Background())
}

func (i *RestAPI) ToRestAPIOutputWithContext(ctx context.Context) RestAPIOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RestAPIOutput)
}

func (i *RestAPI) ToRestAPIPtrOutput() RestAPIPtrOutput {
	return i.ToRestAPIPtrOutputWithContext(context.Background())
}

func (i *RestAPI) ToRestAPIPtrOutputWithContext(ctx context.Context) RestAPIPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RestAPIPtrOutput)
}

type RestAPIPtrInput interface {
	pulumi.Input

	ToRestAPIPtrOutput() RestAPIPtrOutput
	ToRestAPIPtrOutputWithContext(ctx context.Context) RestAPIPtrOutput
}

type restAPIPtrType RestAPIArgs

func (*restAPIPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**RestAPI)(nil))
}

func (i *restAPIPtrType) ToRestAPIPtrOutput() RestAPIPtrOutput {
	return i.ToRestAPIPtrOutputWithContext(context.Background())
}

func (i *restAPIPtrType) ToRestAPIPtrOutputWithContext(ctx context.Context) RestAPIPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RestAPIPtrOutput)
}

// RestAPIArrayInput is an input type that accepts RestAPIArray and RestAPIArrayOutput values.
// You can construct a concrete instance of `RestAPIArrayInput` via:
//
//          RestAPIArray{ RestAPIArgs{...} }
type RestAPIArrayInput interface {
	pulumi.Input

	ToRestAPIArrayOutput() RestAPIArrayOutput
	ToRestAPIArrayOutputWithContext(context.Context) RestAPIArrayOutput
}

type RestAPIArray []RestAPIInput

func (RestAPIArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RestAPI)(nil)).Elem()
}

func (i RestAPIArray) ToRestAPIArrayOutput() RestAPIArrayOutput {
	return i.ToRestAPIArrayOutputWithContext(context.Background())
}

func (i RestAPIArray) ToRestAPIArrayOutputWithContext(ctx context.Context) RestAPIArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RestAPIArrayOutput)
}

// RestAPIMapInput is an input type that accepts RestAPIMap and RestAPIMapOutput values.
// You can construct a concrete instance of `RestAPIMapInput` via:
//
//          RestAPIMap{ "key": RestAPIArgs{...} }
type RestAPIMapInput interface {
	pulumi.Input

	ToRestAPIMapOutput() RestAPIMapOutput
	ToRestAPIMapOutputWithContext(context.Context) RestAPIMapOutput
}

type RestAPIMap map[string]RestAPIInput

func (RestAPIMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RestAPI)(nil)).Elem()
}

func (i RestAPIMap) ToRestAPIMapOutput() RestAPIMapOutput {
	return i.ToRestAPIMapOutputWithContext(context.Background())
}

func (i RestAPIMap) ToRestAPIMapOutputWithContext(ctx context.Context) RestAPIMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RestAPIMapOutput)
}

type RestAPIOutput struct{ *pulumi.OutputState }

func (RestAPIOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RestAPI)(nil))
}

func (o RestAPIOutput) ToRestAPIOutput() RestAPIOutput {
	return o
}

func (o RestAPIOutput) ToRestAPIOutputWithContext(ctx context.Context) RestAPIOutput {
	return o
}

func (o RestAPIOutput) ToRestAPIPtrOutput() RestAPIPtrOutput {
	return o.ToRestAPIPtrOutputWithContext(context.Background())
}

func (o RestAPIOutput) ToRestAPIPtrOutputWithContext(ctx context.Context) RestAPIPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RestAPI) *RestAPI {
		return &v
	}).(RestAPIPtrOutput)
}

type RestAPIPtrOutput struct{ *pulumi.OutputState }

func (RestAPIPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RestAPI)(nil))
}

func (o RestAPIPtrOutput) ToRestAPIPtrOutput() RestAPIPtrOutput {
	return o
}

func (o RestAPIPtrOutput) ToRestAPIPtrOutputWithContext(ctx context.Context) RestAPIPtrOutput {
	return o
}

func (o RestAPIPtrOutput) Elem() RestAPIOutput {
	return o.ApplyT(func(v *RestAPI) RestAPI {
		if v != nil {
			return *v
		}
		var ret RestAPI
		return ret
	}).(RestAPIOutput)
}

type RestAPIArrayOutput struct{ *pulumi.OutputState }

func (RestAPIArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]RestAPI)(nil))
}

func (o RestAPIArrayOutput) ToRestAPIArrayOutput() RestAPIArrayOutput {
	return o
}

func (o RestAPIArrayOutput) ToRestAPIArrayOutputWithContext(ctx context.Context) RestAPIArrayOutput {
	return o
}

func (o RestAPIArrayOutput) Index(i pulumi.IntInput) RestAPIOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) RestAPI {
		return vs[0].([]RestAPI)[vs[1].(int)]
	}).(RestAPIOutput)
}

type RestAPIMapOutput struct{ *pulumi.OutputState }

func (RestAPIMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]RestAPI)(nil))
}

func (o RestAPIMapOutput) ToRestAPIMapOutput() RestAPIMapOutput {
	return o
}

func (o RestAPIMapOutput) ToRestAPIMapOutputWithContext(ctx context.Context) RestAPIMapOutput {
	return o
}

func (o RestAPIMapOutput) MapIndex(k pulumi.StringInput) RestAPIOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) RestAPI {
		return vs[0].(map[string]RestAPI)[vs[1].(string)]
	}).(RestAPIOutput)
}

func init() {
	pulumi.RegisterOutputType(RestAPIOutput{})
	pulumi.RegisterOutputType(RestAPIPtrOutput{})
	pulumi.RegisterOutputType(RestAPIArrayOutput{})
	pulumi.RegisterOutputType(RestAPIMapOutput{})
}
