// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const APIKeySource = {
    HEADER: "HEADER",
    AUTHORIZER: "AUTHORIZER",
} as const;

export type APIKeySource = (typeof APIKeySource)[keyof typeof APIKeySource];

export const Method = {
    ANY: "ANY",
    GET: "GET",
    PUT: "PUT",
    POST: "POST",
    DELETE: "DELETE",
    PATCH: "PATCH",
    OPTIONS: "OPTIONS",
    HEAD: "HEAD",
} as const;

export type Method = (typeof Method)[keyof typeof Method];

export const RequestValidator = {
    ALL: "ALL",
    PARAMS_ONLY: "PARAMS_ONLY",
    BODY_ONLY: "BODY_ONLY",
} as const;

export type RequestValidator = (typeof RequestValidator)[keyof typeof RequestValidator];
