# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'APIKeySource',
    'Method',
    'RequestValidator',
]


class APIKeySource(str, Enum):
    HEADER = "HEADER"
    AUTHORIZER = "AUTHORIZER"


class Method(str, Enum):
    ANY = "ANY"
    GET = "GET"
    PUT = "PUT"
    POST = "POST"
    DELETE = "DELETE"
    PATCH = "PATCH"
    OPTIONS = "OPTIONS"
    HEAD = "HEAD"


class RequestValidator(str, Enum):
    ALL = "ALL"
    PARAM_S_ONLY = "PARAMS_ONLY"
    BOD_Y_ONLY = "BODY_ONLY"
