// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../types";

import * as aws from "@pulumi/aws";

export interface Route {
    contentType?: pulumi.Input<string>;
    data?: any;
    eventHandler?: pulumi.Input<aws.lambda.Function>;
    index?: pulumi.Input<string | boolean>;
    localPath?: pulumi.Input<string>;
    method?: pulumi.Input<enums.Method>;
    path: pulumi.Input<string>;
    target?: pulumi.Input<inputs.Target>;
}

export interface SwaggerGatewayResponse {
    responseParameters?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    responseTemplates?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    statusCode?: pulumi.Input<number>;
}

export interface Target {
    connectionId?: pulumi.Input<string>;
    connectionType?: pulumi.Input<enums.IntegrationConnectionType>;
    httpMethod?: pulumi.Input<"ANY">;
    passthroughBehaviour?: pulumi.Input<enums.IntegrationPassthroughBehavior>;
    type: pulumi.Input<enums.IntegrationType>;
    uri: pulumi.Input<string>;
}
