// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsApiGateway.Inputs
{

    public sealed class RequiredParameterArgs : Pulumi.ResourceArgs
    {
        [Input("in")]
        public Input<string>? In { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public RequiredParameterArgs()
        {
        }
    }
}
