// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Apigateway.Inputs
{

    public sealed class RouteArgs : Pulumi.ResourceArgs
    {
        [Input("contentType")]
        public Input<string>? ContentType { get; set; }

        [Input("data")]
        public Input<object>? Data { get; set; }

        [Input("eventHandler")]
        public Input<Pulumi.Aws.Lambda.Function>? EventHandler { get; set; }

        [Input("index")]
        public InputUnion<string, bool>? Index { get; set; }

        [Input("localPath")]
        public Input<string>? LocalPath { get; set; }

        [Input("method")]
        public Input<Pulumi.Apigateway.Method>? Method { get; set; }

        [Input("path")]
        public Input<string>? Path { get; set; }

        public RouteArgs()
        {
        }
    }
}
