// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsApiGateway.Inputs
{

    public sealed class SwaggerGatewayResponseArgs : Pulumi.ResourceArgs
    {
        [Input("responseParameters")]
        private InputMap<string>? _responseParameters;
        public InputMap<string> ResponseParameters
        {
            get => _responseParameters ?? (_responseParameters = new InputMap<string>());
            set => _responseParameters = value;
        }

        [Input("responseTemplates")]
        private InputMap<string>? _responseTemplates;
        public InputMap<string> ResponseTemplates
        {
            get => _responseTemplates ?? (_responseTemplates = new InputMap<string>());
            set => _responseTemplates = value;
        }

        [Input("statusCode")]
        public Input<double>? StatusCode { get; set; }

        public SwaggerGatewayResponseArgs()
        {
        }
    }
}
