// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Apigateway.Inputs
{

    public sealed class TargetArgs : Pulumi.ResourceArgs
    {
        [Input("connectionId")]
        public Input<string>? ConnectionId { get; set; }

        [Input("connectionType")]
        public Input<Pulumi.Apigateway.IntegrationConnectionType>? ConnectionType { get; set; }

        [Input("httpMethod")]
        public Input<string>? HttpMethod { get; set; }

        [Input("passthroughBehaviour")]
        public Input<Pulumi.Apigateway.IntegrationPassthroughBehavior>? PassthroughBehaviour { get; set; }

        [Input("type", required: true)]
        public Input<Pulumi.Apigateway.IntegrationType> Type { get; set; } = null!;

        [Input("uri", required: true)]
        public Input<string> Uri { get; set; } = null!;

        public TargetArgs()
        {
        }
    }
}
