name: Release provider & SDKs
on:
  workflow_call:
    inputs:
      version:
        description: "Version to be released"
        type: string
        required: true
      publishProvider:
        description: "Publish provider binaries (to GH & S3)"
        default: true
        type: boolean
      publishNpm:
        description: "Publish Node.js SDK"
        default: true
        type: boolean
      publishNuget:
        description: "Publish .NET SDK"
        default: true
        type: boolean
      publishPython:
        description: "Publish Python SDK"
        default: true
        type: boolean
      publishJava:
        description: "Publish Java SDK"
        default: true
        type: boolean
      publishGo:
        description: "Publish Go SDK"
        default: true
        type: boolean
  workflow_dispatch:
    inputs:
      version:
        description: "Version to be released"
        type: string
        required: true
      publishProvider:
        description: "Publish provider binaries (to GH & S3)"
        default: true
        type: boolean
      publishNpm:
        description: "Publish Node.js SDK"
        default: true
        type: boolean
      publishNuget:
        description: "Publish .NET SDK"
        default: true
        type: boolean
      publishPython:
        description: "Publish Python SDK"
        default: true
        type: boolean
      publishJava:
        description: "Publish Java SDK"
        default: true
        type: boolean
      publishGo:
        description: "Publish Go SDK"
        default: true
        type: boolean

env:
  # THIS GITHUB_TOKEN IS A REQUIREMENT TO BE ABLE TO WRITE TO GH RELEASES
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # IF YOU NEED TO PUBLISH A NPM PACKAGE THEN ENSURE A NPM_TOKEN SECRET IS SET
  # IF YOU WANT TO PUBLISH TO A PRIVATE NPM REGISTRY
  # THEN ENSURE THE NPM_REGISTRY_URL IS CHANGED
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_REGISTRY_URL: https://registry.npmjs.org
  # IF YOU NEED TO PUBLISH A NUGET PACKAGE THEN ENSURE AN NUGET_PUBLISH_KEY
  # SECRET IS SET. IF YOU WANT TO PUBLISH TO AN ALTERNATIVE
  # NPM REGISTRY THEN ENSURE THE NPM_REGISTRY_URL IS CHANGED
  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
  NUGET_FEED_URL: https://api.nuget.org/v3/index.json
  # ENSURE AN PYPI_API_TOKEN SECRET IS SET
  # IF YOU WANT TO PUBLISH TO AN ALTERNATIVE
  # PYPI REGISTRY THEN ENSURE THE PYPI_REPOSITORY_URL IS SET. IF YOU ARE USING AN API_TOKEN THEN
  # YOU DO NOT NEED TO CHANGE THE PYPI_USERNAME (__token__) , IF YOU ARE USING PASSWORD AUTHENTICATION THEN YOU WILL
  # NEED TO CHANGE TO USE THE CORRECT PASSWORD
  PYPI_USERNAME: __token__
  PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
  PYPI_REPOSITORY_URL: ""
  # YOU WILL NEED TO SPECIFY A STAGING SERVER AND ITS CREDENTIALS AS WELL AS THE
  # SIGNING INFORMATION FOR THE PACKAGE
  SIGNING_KEY: ${{ secrets.JAVA_SIGNING_KEY }}
  SIGNING_KEY_ID: ${{ secrets.JAVA_SIGNING_KEY_ID }}
  SIGNING_PASSWORD: ${{ secrets.JAVA_SIGNING_PASSWORD }}
  PUBLISH_REPO_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  PUBLISH_REPO_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  PROVIDER_VERSION: ${{ inputs.version }}
  DOTNET_VERSION: "6.x"
  GO_VERSION: "1.21.x"
  JAVA_VERSION: "11"
  NODE_VERSION: "18.x"
  PYTHON_VERSION: "3.9"
  IS_PRERELEASE: ${{ contains(github.ref_name,'-') }}
jobs:
  publish_binary:
    name: Publish Provider Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus2

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: us-east-2
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 3600
          role-external-id: upload-pulumi-release
          role-session-name: uploader@githubActions
          role-to-assume: ${{ secrets.AWS_UPLOAD_ROLE_ARN }}

      - name: Create Provider Binaries
        run: make dist VERSION=${{ inputs.version }}

      - name: Upload to S3
        if: inputs.publishProvider == true
        run: aws s3 cp dist s3://get.pulumi.com/releases/plugins/ --recursive

      - name: Create GitHub Release
        if: inputs.publishProvider == true
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
          prerelease: ${{ env.IS_PRERELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}

  publish_sdk:
    name: Publish SDKs
    runs-on: ubuntu-latest
    needs: publish_binary
    strategy:
      fail-fast: false
      matrix:
        language:
          - nodejs
          - python
          - dotnet
          - go
          - java
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4

      # Required by Makefile::bin/pulumi-java-gen
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: pulumi/pulumictl

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{env.NPM_REGISTRY_URL}}

      - name: Setup DotNet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build SDK
        run: make build_${{ matrix.language }}_sdk VERSION=${{ inputs.version }}

      - name: Check worktree clean
        uses: pulumi/git-status-check-action@v1
        with:
          allowed-changes: |
            sdk/**/pulumi-plugin.json
            sdk/dotnet/Pulumi.*.csproj
            sdk/go/**/pulumiUtilities.go
            sdk/nodejs/package.json
            sdk/python/pyproject.toml

      - name: Publish Python SDK
        if: ${{ inputs.publishPython && matrix.language == 'python' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ env.PYPI_USERNAME }}
          password: ${{ env.PYPI_PASSWORD }}
          packages-dir: ${{github.workspace}}/sdk/python/bin/dist
          skip-existing: true

      - name: Publish Node SDK
        if: ${{ inputs.publishNpm && matrix.language == 'nodejs' }}
        uses: JS-DevTools/npm-publish@v2
        with:
          access: "public"
          token: ${{ env.NPM_TOKEN }}
          package: ${{github.workspace}}/sdk/nodejs/bin/package.json

      - name: Publish NuGet SDK
        if: ${{ inputs.publishNuget && matrix.language == 'dotnet' }}
        run: |
          dotnet nuget push ${{github.workspace}}/sdk/dotnet/bin/Debug/*.nupkg -s ${{ env.NUGET_FEED_URL }} -k ${{ env.NUGET_PUBLISH_KEY }}
          echo "done publishing packages"

      - name: Publish Java SDK
        # Disable Java SDK publishing for pre-release versions
        if: ${{ inputs.publishJava && matrix.language == 'java' && !contains(inputs.version, '-') }}
        uses: gradle/gradle-build-action@v3
        with:
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
          build-root-directory: ./sdk/java
          gradle-version: 8.3

      - uses: pulumi/publish-go-sdk-action@v1
        if: ${{ inputs.publishGo && matrix.language == 'go' }}
        with:
          repository: ${{ github.repository }}
          base-ref: ${{ github.sha }}
          source: sdk
          path: sdk
          version: ${{ inputs.version }}
          additive: false
          # Avoid including other language SDKs & artifacts in the commit
          files: |
            go.*
            go/**
            !*.tar.gz

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: us-west-2
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 3600
          role-session-name: aws-apigateway@githubActions
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}

      - name: Verify nodejs release
        if: ${{ inputs.publishNpm && matrix.language == 'nodejs' }}
        uses: pulumi/verify-provider-release@v1
        with:
          runtime: nodejs
          directory: examples/simple
          provider: aws-apigateway
          providerVersion: ${{ inputs.version }}

      - name: Get python version
        id: python-package-version
        if: ${{ inputs.publishPython && matrix.language == 'python' }}
        run: |
          {
            echo -n "version="
            cat sdk/python/pyproject.toml | sed -nE 's/.*version.*=.*"(.+)"/\1/p'
          } >> "${GITHUB_OUTPUT}"

      - name: Wait for python package to be available
        if: ${{ inputs.publishPython && matrix.language == 'python' }}
        timeout-minutes: 15
        continue-on-error: true
        run: |
          while ! (pip index versions --pre pulumi-aws-apigateway | grep -q " ${{ steps.python-package-version.outputs.version }}"); do sleep 5; done

      - name: Verify python release
        if: ${{ inputs.publishPython && matrix.language == 'python' }}
        uses: pulumi/verify-provider-release@v1
        with:
          runtime: python
          directory: examples/simple-py
          provider: aws-apigateway
          providerVersion: ${{ inputs.version }}
          packageVersion: ${{ steps.python-package-version.outputs.version }}

      - name: Verify go release
        if: ${{ inputs.publishGo && matrix.language == 'go' }}
        uses: pulumi/verify-provider-release@v1
        with:
          runtime: go
          directory: examples/simple-go
          provider: aws-apigateway
          providerVersion: ${{ inputs.version }}
