name: Push Tag
on:
  push:
    tags:
      - v*.*.*
jobs:
  dispatch_publish:
    name: Dispatch Release Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Release Workflow
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: release-test.yaml
          inputs: '{ "version": "${{ github.ref_name }}" }'
