name: Push Tag
on:
  push:
    tags:
      - v*.*.*
jobs:
  version:
    name: Calculate version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.format_version.outputs.version }}
    steps:
      - id: format_version
        # Replace the leading v
        # Outputs must be in the form `var=` so we can access the value
        run: echo "${{ github.ref_name }}" | sed "s/^v/version=/" >> "${GITHUB_OUTPUT}"

  release:
    name: Release
    uses: ./.github/workflows/release.yml
    needs: version
    secrets: inherit
    with:
      version: ${{ needs.version.outputs.version }}
