// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "./types";
import * as utilities from "./utilities";

import * as aws from "@pulumi/aws";

export class RestAPI extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'apigateway:index:RestAPI';

    /**
     * Returns true if the given object is an instance of RestAPI.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RestAPI {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RestAPI.__pulumiType;
    }

    /**
     * The underlying RestAPI resource.
     */
    public /*out*/ readonly api!: pulumi.Output<aws.apigateway.RestApi>;
    /**
     * The underlying RestAPIPolicy resource.
     */
    public /*out*/ readonly apiPolicy!: pulumi.Output<aws.apigateway.RestApiPolicy | undefined>;
    /**
     * The underlying Deployment resource.
     */
    public /*out*/ readonly deployment!: pulumi.Output<aws.apigateway.Deployment>;
    /**
     * The underlying Stage resource.
     */
    public /*out*/ readonly stage!: pulumi.Output<aws.apigateway.Stage>;
    /**
     * The URL where the Rest API is exposed.
     */
    public /*out*/ readonly url!: pulumi.Output<string>;

    /**
     * Create a RestAPI resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: RestAPIArgs, opts?: pulumi.ComponentResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            inputs["apiKeySource"] = args ? args.apiKeySource : undefined;
            inputs["gatewayResponses"] = args ? args.gatewayResponses : undefined;
            inputs["requestValidator"] = args ? args.requestValidator : undefined;
            inputs["routes"] = args ? args.routes : undefined;
            inputs["stageName"] = args ? args.stageName : undefined;
            inputs["staticRoutesBucket"] = args ? args.staticRoutesBucket : undefined;
            inputs["swaggerString"] = args ? args.swaggerString : undefined;
            inputs["api"] = undefined /*out*/;
            inputs["apiPolicy"] = undefined /*out*/;
            inputs["deployment"] = undefined /*out*/;
            inputs["stage"] = undefined /*out*/;
            inputs["url"] = undefined /*out*/;
        } else {
            inputs["api"] = undefined /*out*/;
            inputs["apiPolicy"] = undefined /*out*/;
            inputs["deployment"] = undefined /*out*/;
            inputs["stage"] = undefined /*out*/;
            inputs["url"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(RestAPI.__pulumiType, name, inputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a RestAPI resource.
 */
export interface RestAPIArgs {
    /**
     * The source for the apikey. This can either be a HEADER or AUTHORIZER. If `apiKeyRequired` is
     * set to true on a route, and this is not defined the value will default to HEADER.
     */
    apiKeySource?: enums.APIKeySource;
    /**
     * Define custom gateway responses for the API. This can be used to properly enable
     * CORS for Lambda Authorizers.
     */
    gatewayResponses?: {[key: string]: inputs.SwaggerGatewayResponse};
    /**
     * Request Validator specifies the validator to use at the API level. Note method level validators
     * override this.
     */
    requestValidator?: enums.RequestValidator;
    /**
     * Routes to use to initialize the APIGateway.  These will be used to create the Swagger
     * specification for the API.
     *
     * Either `swaggerString` or `routes` must be specified.
     */
    routes?: pulumi.Input<pulumi.Input<inputs.RouteArgs>[]>;
    /**
     * The stage name for your API. This will get added as a base path to your API url.
     */
    stageName?: pulumi.Input<string>;
    /**
     * Bucket to use for placing resources for static resources.  If not provided a default one will
     * be created on your behalf if any `StaticRoute`s are provided.
     */
    staticRoutesBucket?: pulumi.Input<aws.s3.Bucket>;
    /**
     * A Swagger specification already in string form to use to initialize the APIGateway.  Note
     * that you must manually provide permission for any route targets to be invoked by API Gateway
     * when using `swaggerString`.
     *
     * Either `swaggerString` or `routes` must be specified.
     */
    swaggerString?: pulumi.Input<string>;
}
